# Generated by Django 4.1.7 on 2023-04-11 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["done", "created_date"]},
        ),
    ]
